import{a as f,S as y,i as l}from"./assets/vendor-C9vNCoLC.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const c of r.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&s(c)}).observe(document,{childList:!0,subtree:!0});function o(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=o(t);fetch(t.href,r)}})();f.defaults.baseURL="https://pixabay.com/api/";async function m(e,n){try{return(await f.get("",{params:{per_page:15,page:n,key:"50399513-0102622743a29b0122ce40bab",q:e,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data.hits}catch(o){throw console.log(o,response.status),o}}const h=new y(".gallery a",{captionsData:"alt",captionDelay:250}),p=document.querySelector(".gallery");function g(e){const n=e.map(o=>{const t=["likes","views","comments","downloads"].map(r=>`<p class="info-item">${L(r)}:<span class="info">${o[r]}</span></p>`).join("");return`<li class="image-item">
    <a href="${o.largeImageURL}" title="${o.tags}">
    <img src="${o.webformatURL}" 
    alt="${o.tags}"
    />
    </a>
    <div class="gallery-info">
    ${t}
    </div>
    </li>`}).join("");p.insertAdjacentHTML("beforeend",n),h.refresh()}function L(e){return e&&e.charAt(0).toUpperCase()+e.slice(1).toLowerCase()}function u(){p.innerHTML=""}function b(){const e=document.querySelector(".loader");e&&(e.style.display="inline-block")}function S(){const e=document.querySelector(".loader");e&&(e.style.display="none")}function v(){const e=document.querySelector(".seeMore");e&&(e.style.display="inline-block")}function w(){const e=document.querySelector(".seeMore");e&&(e.style.display="none")}const q=document.querySelector(".form"),a=document.querySelector('input[name="search-text"]'),d=document.querySelector('button[type="submit"]'),M=document.querySelector(".gallery");document.addEventListener("DOMContentLoaded",()=>{i()});w();a.addEventListener("input",i);q.addEventListener("submit",async e=>{e.preventDefault();const n=a.value.trim();if(!i()){l.error({title:"Поле не може бути порожнім",message:"Будь ласка, введіть текст для пошуку.",position:"topRight",timeout:2e3});return}b();try{const o=await m(n);u(M),v(),o.length===0?l.info({title:"Відхилено",message:"За Вашим запитом зображень не знайдено.",position:"topRight"}):g(o)}catch(o){console.error("Помилка під час завантаження зображень:",o),l.error({title:"Помилка",message:"Під час завантаження зображень сталася помилка. Спробуйте ще раз.",position:"topRight"}),u()}finally{S(),a.value="",i()}});function i(){return a.value.trim()!==""?(d.disabled=!1,!0):(d.disabled=!0,!1)}
//# sourceMappingURL=index.js.map
